name: CI

on: [push]

jobs:
  erc-drc-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: PCB/xESC2.kibot.yaml
          board: PCB/xESC2.kicad_pcb
          verbose: 1
